version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Docker-backend
    ports:
      - "8989:8989"
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/check_in
      DB_USERNAME: check_in_dev
      DB_PASSWORD: password
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Docker-fronted
    ports:
      - "3000:80"
    networks:
      - app-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: check_in
      POSTGRES_USER: check_in_dev
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge